### ISSUE TITLE
Clean alternative method for Transliteration mapping

### ISSUE THREAD

**Issue by Ezimetjan** [neouyghur/Uyghur-multi-script-converter-JS#1]
@neouyghur Essalamu eleykum.
I have just come across this repo , took look at it and found it very interesting.  Great work 

I think we could replace the boilerplate expression of the izip() function 

```
function izip(list, values) {
  if (list == null) return {};
  var result = {};
  for (var i = 0, l = list.length; i < l; i++) {
    if (values) {
      result[list[i]] = values[i];
    } else {
      result[list[i][0]] = list[i][1];
    }
  }
  return result;
}

```

with this expression

```
function iZip(list, values) {
  	return  list.reduce((accumulator, value, index) => (accumulator[value] = values[index], accumulator), {});
}

```
I wanted to fork the project and make a pull request, but i was in a rush.  Please do consider using above method if you find it ideal, i think its much cleaner .

**Comment by neouyghur** [comment]
@Ezimetjan  Thanks for commenting. I am a newbie to javascript. I didn't understand your code, but I tested it. It doesn't work. Could you test it? Rexmet.

**Comment by Ezimetjan** [comment]
@neouyghur I have just created a sample project on my repo https://github.com/Ezimetjan/Uyghur-Script-Transliteration,  it seems above code is working fine for me,  what error did you see from console log?  please take look at the sample project, it should be working.

**Comment by neouyghur** [comment]
@Ezimetjan  I found the problem. It is because of the function name. I integrated it. Thanks. And I hope you can refer my project in your project. Thanks.
